# -*- coding: utf-8 -*-
"""Laboratorio entregable 20 Blanca

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFIkWUjascWBxZlxkgDKloiXu2j2HtdF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#1. Cargar los datos desde el CSV generado
df_financiero = pd.read_csv('/content/datos_financieros.csv')
#2. Exploracion de los datos
print("Resumen de los datos:")
print(df_financiero.describe(include='all'))

print("\nVerificación de valores nulos:")
print(df_financiero.isnull().sum())

#3. Limpieza de datos
df_financiero['Salario_Anual'] = df_financiero['Salario_Anual'].fillna(df_financiero['Salario_Anual'].median())
df_financiero['Deuda'] = df_financiero['Deuda'].fillna(df_financiero['Deuda'].median())

# Verificar la limpieza
print("\nVerificación de valores nulos después de la limpieza:")
print(df_financiero.isnull().sum())

#Exportar los datos limpios a un nuevo archivo CSV
df_financiero.to_csv('datos_financieros_limpios.csv', index=False)

# Visualizacion personalizada
plt.figure(figsize=(10, 6))
plt.scatter(df_financiero['Edad'], df_financiero['Deuda'], c='green', alpha=0.5)
plt.title('Relación entre Edad y Deuda', fontsize=15)
plt.xlabel('Edad', fontsize=12)
plt.ylabel('Deuda', fontsize=12)
plt.grid(True)
# Añadir una linea de tendencia
z = np.polyfit(df_financiero['Edad'], df_financiero['Deuda'], 1)
p = np.poly1d(z)
plt.plot(df_financiero['Edad'], p(df_financiero['Edad']), color='red', label='Tendencia')
plt.legend()
plt.tight_layout()
plt.show()
print()
# Grafica de barras
plt.figure(figsize=(8, 6))
df_financiero['Historial_Crediticio'].value_counts().plot(kind='bar', color='skyblue', edgecolor='black')
plt.title('Distribución del Historial Crediticio', fontsize=15)
plt.xlabel('Historial Crediticio', fontsize=12)
plt.ylabel('Cantidad de Clientes', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)